using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Threading;

namespace Caches
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Thread.Sleep(10000);
            Response.Write("this page was generated by cache at:" + DateTime.Now.ToString());
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            Response.Write("<br><br>");
            Response.Write("<h2>Hello," + this.TextBMagic.Text + "</h2>");
        }
    }
}